/*Even Fibonacci numbers
Problem 2
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/

var zeroNum = 0;
var firstNum = 1;
var secNum = 2;
var fibonacci_Array = [];
var sum = 0;
var limit = 10;

fibonacci_Array.push(zeroNum);
fibonacci_Array.push(firstNum);
while (secNum < 4000000){
  fibonacci_Array.push(secNum);
  secNum = firstNum + secNum;
  firstNum = secNum - firstNum;
}
for ( i = 0; i <= fibonacci_Array.length; i++ ) {
    if (fibonacci_Array[i] % 2 === 0)
    sum = fibonacci_Array[i] + sum;
}

console.log(fibonacci_Array);
console.log(sum);
